version: 1.2
workflows:
  - name: ONT_RefAssembly
    subclass: wdl
    primaryDescriptorPath: /wdls/workflows/ONT_RefAssembly.wdl
    latestTagAsDefault: 'true'
    authors:
      - orcid: "0000-0002-6006-0641"
